import Commonlayout from "./Components/Common/Commonlayout";
import Footer from "./Components/Common/Footer";
import Header from "./Components/Common/Header";
import "./globals.css";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Commonlayout>

          {children}

        </Commonlayout>
      </body>
    </html>
  );
}
