import React from 'react'
import ProductListing from '../Components/ProductListing';
import { brands, getCategories } from '../Services/ApiServices';

export const metadata = {
  title: "Product Listings",
  description: "Generated by create next app",
};

export default async function page() {

  var getCategory = await getCategories();
  var getBrands = await brands();

  return (
    <>
    <ProductListing getCategory={getCategory} getBrands={getBrands}/>
    </>
  )
}
